function AEvent:GetPhrase(str)
    return AEvent.Languages[AEvent.Language][str]
end

AEvent.Languages["en"] = {
    ["addon_name"] = "Advanced Event System",
    ["id_dosnt_exist"] = "ID: %s dosnt exist!",
    ["bad_id"] = "BAD ID",
    ["successfully_started"] = "Successfully started",
    ["success"] = "Success",
    ["dont_have_rank"] = "You dont have the correct rank ):",
    ["delete_sure"] = "Are you sure you want to delete this?",
    ["confirmation"] = "Confirmation",
    ["yes"] = "Yes",
    ["no"] = "No",
    ["back"] = "Back",
    ["save"] = "Save",
    ["hook_limit"] = "You have reached the hook limit",
    ["sure_start"] = "Are you sure you want to start the event?",
    ["event_name"] = "Event Name",
    ["broken_command"] = "BROKEN COMMAND PLEASE FIX OR DELETE THIS LINE",
    ["delete"] = "Delete",
    ["insert_above"] = "Insert above",
    ["end_event"] = "END THE CURRENT EVENT",
    ["create_event"] = "CREATE EVENT",
    ["rename"] = "Rename",
    ["input_name"] = "Input a new name",
    ["preset_maker"] = "Preset Maker",
    ["create_preset"] = "CREATE PRESET",
    ["kill_box"] = "Kill Box",
    ["props"] = "Props",
    ["box"] = "Box (players can teleport here)",

    ["left_click"] = "Left click to start the proccess; Left click again to finish",
    ["right_click"] = "Right click to open the editor",
    ["search"] = "Search"
}

AEvent.Languages["de"] = {
    ["addon_name"] = "Erweitertes Event System",
    ["id_dosnt_exist"] = "ID: %s existiert nicht!",
    ["bad_id"] = "FALSCHE ID",
    ["successfully_started"] = "Erfolgreich gestartet!",
    ["success"] = "Erfolg!",
    ["dont_have_rank"] = "Sie haben nicht den richtigen Rang!",
    ["delete_sure"] = "Seien sie sicher das ihr dies löschen möchten?",
    ["confirmation"] = "Konfirmation",
    ["yes"] = "Ja",
    ["no"] = "Nein",
    ["back"] = "Zurück",
    ["save"] = "Speichern",
    ["hook_limit"] = "Sie haben die 'hook' grenze erreicht!",
    ["sure_start"] = "Seien sie euch sicher, dass ihr den Event starten wollen?",
    ["event_name"] = "Event Name",
    ["broken_command"] = "DIESER BEFEHL FUNKTIONIERT NICHT, BITTE REPARIEREN ODER LÖSCHEN",
    ["delete"] = "löschen",
    ["insert_above"] = "Oben einfügen",
    ["end_event"] = "BEENDEN DAS AKTUELLE EVENT",
    ["create_event"] = "EVENT ERSTELLEN",
    ["rename"] = "umbenennen",
    ["input_name"] = "Den neuen name eingeben",
    ["preset_maker"] = "'Preset-Ersteller'",
    ["create_preset"] = "Preset Erstellen",
    ["kill_box"] = "Tötungs Kiste",
    ["props"] = "Props",
    ["box"] = "Kiste (Spieler können hier ein teleportieren)",

    ["left_click"] = "Links drücken um den Prozess zu starten; Wieder links drücken um den Prozess zu fertigen",
    ["right_click"] = "Rechts drücken um den Configurator zu öffnen",
    ["search"] = "Suchen",
}

AEvent.Languages["fr"] = {
    ["addon_name"] = "System d'Event Avancé",
    ["id_dosnt_exist"] = "La ID: %s n'existe pas!",
    ["bad_id"] = "MAUVAISE ID",
    ["successfully_started"] = "Commencé sans problemes!",
    ["success"] = "Success!",
    ["dont_have_rank"] = "Vous n'avez pas le rang correcte!",
    ["delete_sure"] = "Êtes vous sûre de supprimer celà?",
    ["confirmation"] = "Confirmation",
    ["yes"] = "Oui",
    ["no"] = "Non",
    ["back"] = "Arrière",
    ["save"] = "Sauvegarder",
    ["hook_limit"] = "Vous avez atteint la limite de 'hooks'!",
    ["sure_start"] = "Etes vous sûre de commencer l'Event?",
    ["event_name"] = "Nom de l'Event",
    ["broken_command"] = "COMMANDE QUI NE MARCHE PAS! REPARER OU SUPPRIMER CETTE LIGNE",
    ["delete"] = "Supprimer",
    ["insert_above"] = "Inserez dessus",
    ["end_event"] = "Terminer l'Event actuelle",
    ["create_event"] = "Créer un Event",
    ["rename"] = "Renommer",
    ["input_name"] = "Inserez un nouveau nom",
    ["preset_maker"] = "Créateur de Preset",
    ["create_preset"] = "Créer un preset",
    ["kill_box"] = "Boîte de mort",
    ["props"] = "Props",
    ["box"] = "Boîte (Les joueurs peuvent se teleporter ici)",
    ["left_click"] = "Souris gauche pour commencer proccess; Souris gauche une deuxieme fois pour terminer",
    ["right_click"] = "Souris droite pour ouvrir le configurateur",
    ["search"] = "Recherche",
}

AEvent.Languages["tr"] = {
    ["addon_name"] = "Gelişmiş Etkinlik Sistemi",
    ["id_dosnt_exist"] = "Kimlik: %s mevcut değil!",
    ["bad_id"] = "GEÇERSİZ KİMLİK",
    ["successfully_started"] = "Başarıyla başladı",
    ["success"] = "Başarılı",
    ["dont_have_rank"] = "Doğru rütbeniz yok ):",
    ["delete_sure"] = "Bunu silmek istediğinizden emin misiniz?",
    ["confirmation"] = "Onay",
    ["yes"] = "Evet",
    ["no"] = "Hayır",
    ["back"] = "Geri",
    ["save"] = "Kaydet",
    ["hook_limit"] = "Kanca sınırına ulaştınız",
    ["sure_start"] = "Etkinliği başlatmak istediğinizden emin misiniz?",
    ["event_name"] = "Etkinlik Adı",
    ["broken_command"] = "BOZUK KOMUT LÜTFEN DÜZELTİN VEYA BU SATIRI SİLİN",
    ["delete"] = "Sil",
    ["insert_above"] = "Üstüne ekle",
    ["end_event"] = "MEVCUT ETKİNLİĞİ SONLANDIR",
    ["create_event"] = "ETKİNLİK OLUŞTUR",
    ["rename"] = "Yeniden Adlandır",
    ["input_name"] = "Yeni bir ad girin",
    ["preset_maker"] = "Ön Ayar Oluşturucu",
    ["create_preset"] = "ÖN AYAR OLUŞTUR",
    ["kill_box"] = "Öldürme Kutusu",
    ["props"] = "Özellikler",
    ["box"] = "Kutu (oyuncular buraya teleport yapabilir)",
    ["left_click"] = "İşlemi başlatmak için sol tıklayın; İşlemi bitirmek için tekrar sol tıklayın",
    ["right_click"] = "Düzenleyiciyi açmak için sağ tıklayın",
    ["search"] = "Arama",
}